name: Metrics 2
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.extra.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_user: GillianMC
          plugin_anilist_medias: anime, amnga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 1
          plugin_steam: yes
          plugin_steam_user: "76561198857530309"
          plugin_steam_sections: player, recently-played
          plugin_steam_achievements_limit: 2
