name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          config_timezone: Europe/Kyiv
          config_display: columns
          
          plugin_languages: yes
          plugin_languages_ignored: c++, c#, cmake, objective-c, makefile, java, ruby, starlark
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_traffic: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_anilist: yes
          plugin_anilist_user: GillianMC
          plugin_anilist_medias: anime, amnga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 1
          plugin_steam: yes
          plugin_steam_user: "76561198857530309"
          plugin_steam_sections: player, recently-played
          plugin_steam_achievements_limit: 2
