name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: columns
          config_output: png
          
          plugin_languages: yes
          plugin_languages_skipped: metrics, SteamAchievementManager, GameTrackerHLTBAndroid
          plugin_languages_ignored: c++, cmake, makefile, java, ruby, starlark
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_traffic: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0